### ISSUE TITLE
Registration objects are not immediately serializable

### ISSUE THREAD

**Issue by ryankurte** [tstranex/u2f#11]
Hey there,

I see you have elected to make a breaking API change to support the new U2F API format, are you open to other breaking changes?

Would be super useful if the objects returned from the API only used go primitives to simplify serialisation into session or data stores.

For example, the public key and attestation certificates in the Registration structure have to be manually coerced into ASN1 strings to store in a relational database.
This could be wrapped in the API to make the library simpler to use.

I am happy to open a PR if you're open to that idea?

Cheers,

Ryan

**Comment by tstranex** [comment]
Hi Ryan

Registration does have MarshalBinary and UnmarshalBinary methods for storing the Registration in a db. I think it's generally better to store the raw binary data instead of parsing and then serializing it again because e.g. the data may come from a newer token version that has fields that the parser ignores. You can always store extra structured fields in addition to the raw binary in your db (e.g. the key handle or attestation cert serial).

Regards,
Timothy
